export const TOKEN_NAME = "access_token";

export const IDGobPeConst = {
    ACR_ONE_FACTOR: 'one_factor',
    ACR_CERTIFICATE_DNIE: 'certificate_dnie',
    ACR_CERTIFICATE_TOKEN: 'certificate_token',
    ACR_CERTIFICATE_DNIE_LEGACY: 'certificate_dnie_legacy',
    ACR_CERTIFICATE_TOKEN_LEGACY: 'certificate_token_legacy',
    PROMPT_NONE: 'none',
    PROMPT_LOGIN: 'login',
    PROMPT_CONSENT: 'consent',
    SCOPE_PROFILE: 'profile',
    SCOPE_EMAIL: 'email',
    SCOPE_PHONE: 'phone',
    SCOPE_OFFLINE_ACCESS: 'offline_access',
    RESPONSE_TYPE_CODE: 'code',
    RESPONSE_TYPE_ID_TOKEN: 'id_token',
    RESPONSE_TYPE_TOKEN: 'token',
    EVENT_LOADED: 'IDGobPe_loaded',
    EVENT_CONNECTED: 'IDGobPe_connected',
    EVENT_CANCEL: 'IDGobPe_cancel',
    ERROR_INVALID_ORIGIN_JS: 'IDGobPe_invalid_origin_js',
    EVENT_AUTH_COMPLETE: 'IDGobPe_auth_complete',
    EVENT_RELOAD: 'IDGobPe_reload',
    EVENT_AUTH_RELOAD: 'IDGobPe_auth_reload',
    EVENT_AUTH_CANCEL: 'IDGobPe_auth_cancel',
};

export const IDGobPeErrors = [
    { "code": "internal_error", "message": "Internal error" ,"img":"expirado.png"},
    { "code": "invalid_request", "message": "Invalid parameters" ,"img":"expirado.png"},
    { "code": "invalid_redirect_uri", "message": "Invalid redirect uri" ,"img":"expirado.png"},
    { "code": "invalid_origin_js", "message": "No matching origin uri" ,"img":"expirado.png"},
    { "code": "origin_js_not_found", "message": "No matching origin uri" ,"img":"expirado.png"},
    { "code": "redirect_uri_not_found", "message": "" ,"img":"expirado.png"},
    { "code": "acr_values_wrong", "message": "" ,"img":"expirado.png"},
    { "code": "client_not_found", "message": "" ,"img":"expirado.png"},
    { "code": "client_wrong_credentials", "message": "Invalid client credentials" ,"img":"expirado.png"},
    { "code": "redirect_uri_not_match", "message": "" ,"img":"expirado.png"},
    { "code": "origin_js_not_match", "message": "" ,"img":"expirado.png"},
    { "code": "response_type_token_alone", "message": "Token response_type not work alone." ,"img":"expirado.png"},
    { "code": "response_type_wrong", "message": "" ,"img":"expirado.png"},
    { "code": "code_challenge_required", "message": "" ,"img":"expirado.png"},
    { "code": "code_challenge_unsupported", "message": "unsupported code challenge method" ,"img":"expirado.png"},
    { "code": "nonce_not_found", "message": "" ,"img":"expirado.png"},
    { "code": "unable_to_decrypt_request_object", "message": "Unable to decrypt request object" ,"img":"expirado.png"},
    { "code": "unable_to_validate_sign_request_object", "message": "Unable to verify request object signature" ,"img":"expirado.png"},
    { "code": "idtoken_hint_wrong_userid", "message": "Unrecognized userid in ID Token." ,"img":"expirado.png"},
    { "code": "requested_user_diff_logged", "message": "Requested user is different from logged in user, no UI requested" ,"img":"expirado.png"},
    { "code": "prompt_none_max_age", "message": "max_age exceeded and prompt set to none" ,"img":"expirado.png"},
    { "code": "prompt_none_consent", "message": "Consent needed and prompt set to none" ,"img":"expirado.png"},
    { "code": "prompt_none_unauthenticated", "message": "Unauthenticated and prompt set to none" ,"img":"expirado.png"},
    { "code": "prompt_conflicting", "message": "Conflicting prompt parameters" ,"img":"expirado.png"},
    { "code": "user_disabled", "message": "User disabled" ,"img":"expirado.png"},
    { "code": "user_locked", "message": "User locked" ,"img":"expirado.png"},
    { "code": "user_not_exists", "message": "User not exist" ,"img":"expirado.png"},
    { "code": "token_idp_not_found", "message": "No tokenIdp in request" ,"img":"expirado.png"},
    { "code": "token_idp_acr_not_match", "message": "acr not match" ,"img":"expirado.png"},
    { "code": "token_idp_is_revoked", "message": "token is revoked" ,"img":"expirado.png"},
    { "code": "auth_code_wrong", "message": "No auth code in request" ,"img":"expirado.png"},
    { "code": "auth_code_not_exist", "message": "No exist code or Access token expired" ,"img":"expirado.png"},
    { "code": "code_verified_wrong", "message": "code_verifier required" ,"img":"expirado.png"},
    { "code": "code_verified_mismatch", "message": "code_verifier mismatch" ,"img":"expirado.png"},
    { "code": "id_token_crypto_error", "message": "Idtoken crypto error" ,"img":"expirado.png"},
    { "code": "refresh_token_not_exist", "message": "No exist refresh token or Refresh token expired." ,"img":"expirado.png"},
    { "code": "refresh_token_wrong_client", "message": "Invalid token for client" ,"img":"expirado.png"},
    { "code": "refresh_token_scope_not_match", "message": "Scope not match with original token" ,"img":"expirado.png"},
    { "code": "client_assertion_unknown", "message": "Unknown client_assertion_type" ,"img":"expirado.png"},
    { "code": "client_assertion_not_available", "message": "client_assertion not available" ,"img":"expirado.png"},
    { "code": "jwt_iss_sub_mismatch", "message": "JWT iss and sub mismatch" ,"img":"expirado.png"},
    { "code": "authentication_type_unknown", "message": "Unknown authentication type" ,"img":"expirado.png"},
    { "code": "authentication_type_mismatched", "message": "mismatched token endpoint auth type" ,"img":"expirado.png"},
    { "code": "secret_client_wrong", "message": "No client or secret" ,"img":"expirado.png"},
    { "code": "secret_client_wrong", "message": "grant_type not supported" ,"img":"expirado.png"},
    { "code": "access_token_not_found", "message": "No access token" ,"img":"expirado.png"},
    { "code": "access_token_not_found", "message": "Cannot find access token or Access token expired" ,"img":"expirado.png"},
    { "code": "time_expired", "message": "Time to complete login has expired." ,"img":"expirado.png"},
    { "code": "token_not_exist", "message": "El token ingresado no existe." ,"img":"expirado.png"},
    { "code": "wrong_token", "message": "El código ingresado es incorrecto o ha expirado." ,"img":"expirado.png"},
    { "code": "error_retry", "message": "Ha ocurrido un error, por favor vuelve a intentarlo más tarde.","img":"expirado.png" }
];