export const TOKEN_NAME = "access_token";

export const _IDGobPeConst = {
    ACR_ONE_FACTOR: 'one_factor',
    ACR_CERTIFICATE_DNIE: 'certificate_dnie',
    ACR_CERTIFICATE_TOKEN: 'certificate_token',
    ACR_CERTIFICATE_DNIE_LEGACY: 'certificate_dnie_legacy',
    ACR_CERTIFICATE_TOKEN_LEGACY: 'certificate_token_legacy',
    PROMPT_NONE: 'none',
    PROMPT_LOGIN: 'login',
    PROMPT_CONSENT: 'consent',
    SCOPE_PROFILE: 'profile',
    SCOPE_EMAIL: 'email',
    SCOPE_PHONE: 'phone',
    SCOPE_OFFLINE_ACCESS: 'offline_access',
    RESPONSE_TYPE_CODE: 'code',
    RESPONSE_TYPE_ID_TOKEN: 'id_token',
    RESPONSE_TYPE_TOKEN: 'token',
    EVENT_LOADED: 'IDGobPe_loaded',
    EVENT_CONNECTED: 'IDGobPe_connected',
    EVENT_CANCEL: 'IDGobPe_cancel',
    ERROR_INVALID_ORIGIN_JS: 'IDGobPe_invalid_origin_js',
    EVENT_AUTH_COMPLETE: 'IDGobPe_auth_complete',
    EVENT_RELOAD: 'IDGobPe_reload',
    EVENT_AUTH_RELOAD: 'IDGobPe_auth_reload',
    EVENT_AUTH_CANCEL: 'IDGobPe_auth_cancel',
};